#!/usr/bin/perl
  use strict;
  use warnings;
  use feature 'say';
  my @data;

open (MYFILE, '<input_file.txt'); ### открываем файл, записываем в массив дата, используем < для указания только чтения

@data = <MYFILE>;               ### так как где-то прочитал,что это хороший тон и,цитирую, "не позволяет хакнуть скрипт"

close (MYFILE);


$h{$_}+=1 foreach @data;                #### по идее подсчитывает количество одинаковых элементов в массиве и делает хэш
@k = keys %h; 
say "$_ : $h{$_}" foreach (@k);
