#!/usr/bin/perl
use Getopt::Long ;
my $name;
GetOptions ("name=s" => \$name );
open FILE, ">", $name or die $!;

  undef(local $/);
  my $text = <FILE>;

close (FILE);

my @list = split(//, $text);
my %h;


$h{$_}++ foreach (@list);


foreach (keys %h) {
          $_=$h{$_};
}
     
     
          foreach(sort {$h{$a} <=> $h{$b}} keys %h) {
          print $_,'=',$h{$_},"\n";
}
